INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (7, 'Заместитель генерального директора по координации разработки', 6, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (47, 'Администратор проекта', 10, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (48, 'Главный эксперт', 11, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (49, 'Ведущий специалист', 12, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (45, 'Заместитель начальника управления', 8, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (54, 'Начальник отдела (Руководитель команды)', 13, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (56, 'Главный бухгалтер', 14, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (57, 'Специалист по бухгалтерскому учету и отчетности ', 15, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (58, 'Специалист по охране труда', 16, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (59, 'Специалист по административно-хозяйственному обеспечению', 17, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (60, 'Специалист по подбору персонала', 18, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (61, 'Руководитель направления закупочной деятельности', 19, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (62, 'Руководитель направления кадрового администрирования', 20, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (63, 'Руководитель направления правового обеспечения', 21, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (64, 'Юрист', 22, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (65, 'Руководитель отдела тестирования', 23, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (66, 'Главный тестировщик', 24, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (67, 'Ведущий тестировщик', 25, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (68, 'Тестировщик', 26, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (69, 'Руководитель проекта', 27, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (70, 'Заместитель руководителя ', 28, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (71, 'Главный аналитик', 29, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (72, 'Ведущий аналитик', 30, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (73, 'Старший аналитик', 31, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (74, 'Администратор', 32, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (75, 'Аналитик', 33, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (76, 'Ведущий аналитик СУИД', 34, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (77, 'Младший аналитик', 35, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (78, 'Аналитик-координатор', 36, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (80, 'Ведущий разработчик', 37, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (83, 'Специалист по цифровым решениям', 38, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (90, 'Главный разработчик I категории', 39, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (91, 'Главный разработчик II категории', 40, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (92, 'Старший разработчик I категории', 41, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (93, 'Старший разработчик II категории', 42, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (94, 'Старший разработчик III категории', 43, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (95, 'Старший разработчик IV категории', 44, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (96, 'Разработчик II категории', 45, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (97, 'Разработчик III категории', 46, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (98, 'Разработчик IV категории', 47, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (99, 'Специалист по цифровым решениям I категории', 48, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (100, 'Специалист по цифровым решениям II категории', 49, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (101, 'Специалист по цифровым решениям III категории', 50, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (102, 'Специалист по цифровым решениям IV категории', 51, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (103, 'Специалист по цифровым решениям V категории', 52, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (104, 'Специалист по цифровым решениям IV категории', 53, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (105, 'Разработчик I категории', 54, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (106, 'Руководитель проектов по эксплуатации информационных систем', 55, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (107, 'Начальник отдела - Руководитель блока', 56, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (108, 'Ведущий специалист информационной безопасности', 57, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (109, 'Специалист информационной безопасности', 58, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (110, 'Архитектор', 59, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (111, 'Системный администратор', 60, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (112, 'Технический писатель', 61, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (113, 'Системный инженер I категории', 62, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (114, 'Системный инженер II категории', 63, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (115, 'Системный инженер III категории', 64, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (116, 'Системный инженер IV категории', 65, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (117, 'Ведущий дизайнер интерфейсов', 66, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (118, 'Специалист технической поддержки', 67, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (119, 'Дизайнер интерфейсов', 68, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (120, 'Дизайнер', 69, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (8, 'Исполнительный директор', 0, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (4, 'Заместитель генерального директора по координации реализации планов ОИВ', 1, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (2, 'Заместитель руководителя департамента', 4, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (3, 'Генеральный директор', 2, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (41, 'Главный специалист', 3, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (46, 'Руководитель проекта', 9, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (5, 'Заместитель генерального директора по координации аналитики', 5, false, null, false);
INSERT INTO public.positions (position_id, name, sort, deleted, deleted_at, is_category) VALUES (44, 'Начальник управления', 7, false, null, false);
