INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (21, 'Администрация', null, null, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (22, 'Управление', null, 39, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (23, 'Управление цифровизации и градостроительных данных', 22, null, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (24, 'Управление цифрового развития', 22, null, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (25, 'Отдел координации реализации планов ОИВ', null, 50, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (26, 'Отдел координации аналитики ПО Строительство', null, 51, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (27, 'Отдел координации аналитики ПО Земля', null, 51, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (28, 'Отдел координации аналитики ПО Градрешения', null, 51, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (29, 'Отдел координации аналитики ПО Аналитики и Мониторинга', null, 51, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (30, 'Отдел координации разработки', null, 52, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (31, 'Отдел инженерного обеспечения', null, 52, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (33, 'Отдел координации деятельности', null, 53, false, null);
INSERT INTO public.departments (department_id, name, parent_department_id, parent_position_id, deleted, deleted_at) VALUES (32, 'Отдел тестирования', null, 52, false, null);
