INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (7, 'ИАС УГД', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (8, 'ЕИС МГЗ', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (11, 'СтройМос', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (12, 'СтроимПросто', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (13, 'Строймониторинг', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (14, 'SuperSet', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (15, 'АИС РЕОН', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (16, 'АИС РСМ', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (17, 'СУИД', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (18, 'BS', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (19, 'KPI', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (20, 'Рейтинг ОИВ', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (21, 'Производственные программы', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (22, 'ДБ Аналитика ', 'ДБ Аналитика (Сенина)', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (23, 'EXON', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (9, 'СУПД АКЦЕНТ', '', null, false, null);
INSERT INTO public.projects (project_id, name, description, department_id, deleted, deleted_at) VALUES (10, 'ИАС ОГД', '', null, false, null);
